# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    curl \
    ncat \
    traceroute \ 
    nmap

# Use a virtual environment to avoid running pip as root
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


WORKDIR /root
COPY .bashrc .bashrc

# Set the working directory to /app
WORKDIR /app

# Copy shell spy wrapper
COPY ./bash.sh /bin/bash.sh 

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

VOLUME [ "/history" ]
ENV HISTFILE="/history/.bash_history"
WORKDIR /history
RUN touch .bash_history
WORKDIR /app
